name: cz-web build
# 触发workflow的条件
on:
    push:
        # 只有main分支发生push事件时，才会触发workflow
        branches: [main]
    pull_request:
        branches: [main]

env:
    SERVER_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }} # 服务器私钥
    SERVER_HOST: ${{ secrets.SERVER_HOST }} # 服务器IP地址
    USER_NAME: ${{ secrets.USER_NAME }} # 服务器用户名
    cache-name: note

# jobs表示执行的一项或多项任务
jobs:
    build: # 任务的job_id，具体名称自定义，这里build代表打包
        runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
        steps:
            - uses: actions/checkout@main
            - name: Setup PNPM
              uses: pnpm/action-setup@v2.2.1
              with:
                version: ^7.0

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 16
                cache: "pnpm"

            #缓存依赖
            - name: Cache nodemodules
              uses: actions/cache@v1
              env:
                  cache-name: cache-node-modules
              with:
                  # 需要缓存的文件的路径
                  path: ./node_modules
                  # 对缓存的文件指定的唯一标识
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package.json') }}
                  # 用于没有再找目标key的缓存的backup选项
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            # 装依赖
            - name: Install
              run: pnpm i --no-frozen-lockfile

            # 打包
            - name: Build Web
              run: pnpm build

            # 上传打包资源
            - name: Deploy Web
              uses: appleboy/scp-action@master
              with:
                  source: "dist/*"
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.USER_NAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: 22
                  target: "/www/wwwroot/www.czstudio.tech/" # 服务器目标路径

            - name: Move files
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.USER_NAME }}
                password: ${{ secrets.PASSWORD }}
                port: 22
                script: |
                  mv /www/wwwroot/www.czstudio.tech/dist/* /www/wwwroot/www.czstudio.tech/

            # 打包文档库
            - name: Build Docs
              run: pnpm docs:build

            # 上传打包资源
            - name: Deploy Docs
              uses: appleboy/scp-action@master
              with:
                  source: "docs/.vitepress/dist/*"
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.USER_NAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: 22
                  target: "/www/wwwroot/docs.czstudio.tech/" # 服务器目标路径

            - name: Move files
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.USER_NAME }}
                password: ${{ secrets.PASSWORD }}
                port: 22
                script: |
                  mv /www/wwwroot/docs.czstudio.tech/dist/* /www/wwwroot/docs.czstudio.tech/
